baseURL: https://colecornford.com
languageCode: en-us
defaultContentLanguage: en
title: Cole Cornford
theme: cupper-hugo-theme
googleAnalytics: 
disqusShortname: 
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Security, Gaming, Travel, and other interests!
  homeMetaContent: Security, Gaming, Travel, and other interests!
  footer: (c) Cole Cornford 2020
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  customCss:
  customJs:
menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Resources
      url: /resources/
      weight: 4
    - name: Projects
      url: /projects/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: github
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
