baseURL = "https://www.colecornford.com"
DefaultContentLanguage = "en"
title = "Cole Cornford"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "colecornford"
disableFastRender=true


[Params]
  homeTitle = "Hi, I'm Cole!"
  subtitle = "AppSec and DevSecOps Specialist + Security Speaker"
  logo = "img/birb.jpeg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Author]
  name = "Cole Cornford"
  github = "colecornford"
  twitter = "colecornford"
  linkedin = "colecornford"

[[menu.main]]
    name = "Start Here!"
    url = "page/start"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "page/projects/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 4